channel: stable
addons:
  lovelace-kindle-screensaver:
    repository: marciogranzotto/hass-lovelace-kindle-screensaver
    target: lovelace-kindle-screensaver
    image: marciogranzotto/addon-lovelace-kindle-screensaver-{arch}

